version: 2.1
jobs:
  build:
    docker:
      - image: php:7.2.17-fpm-stretch
    steps:
      - checkout
      - run: apt update
      - run: apt install -y libpng-dev sqlite
      - run: docker-php-ext-install pdo pdo_sqlite gd
      - run: composer install
      - run: npm install
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --force
      - run: ./vendor/bin/phpunit
